POST https://api-bgb.herokuapp.com/submit
content-type: application/json

{
   "auth_date":1650650191,
   "first_name":"Rodrigo",
   "hash":"4b46f065d4d8ab475b1e83e171b0355aadc8dce5d3e04b2add28e1e87d9981b5",
   "id":1404345981,
   "last_name":"None",
   "photo_url":"None",
   "status":"success",
   "username":"julioscalves",
   "city":"Recife",
   "state":"PE",
   "general_description":"",
   "ending_date":"",
   "boardgames":[
      {
         "id":8109,
         "name":"Mansions of Madness: Segunda Edição – Caminho da Serpente: Expansão",
         "description":"Avariado",
         "price":"100,00",
         "type":"Apenas Venda"
      },
      {
         "id":8109,
         "name":"Mansions of Madness: Segunda Edição – Caminho da Serpente: Expansão",
         "description":"Avariado",
         "price":"100,00",
         "type":"Apenas Venda"
      },
      {
         "id":8109,
         "name":"Mansions of Madness: Segunda Edição – Caminho da Serpente: Expansão",
         "description":"Avariado",
         "price":"100,00",
         "type":"Apenas Venda"
      },
      {
         "id":8109,
         "name":"Mansions of Madness: Segunda Edição – Caminho da Serpente: Expansão",
         "description":"Avariado",
         "price":"100,00",
         "type":"Apenas Venda"
      },
      {
         "id":8109,
         "name":"Mansions of Madness: Segunda Edição – Caminho da Serpente: Expansão",
         "description":"Avariado",
         "price":"100,00",
         "type":"Apenas Venda"
      },
      {
         "id":7873,
         "name":"Mansions of Madness: Segunda edição – Santuário do Crepúsculo: Expansão",
         "description":"Zerado.",
         "price":"299,00",
         "type":"Apenas Troca"
      },
      {
         "id":8109,
         "name":"Mansions of Madness: Segunda Edição – Caminho da Serpente: Expansão",
         "description":"Avariado",
         "price":"100,00",
         "type":"Apenas Troca"
      },
      {
         "id":8109,
         "name":"Mansions of Madness: Segunda Edição – Caminho da Serpente: Expansão",
         "description":"Avariado",
         "price":"100,00",
         "type":"Apenas Troca"
      },
      {
         "id":386,
         "name":"Mansions of Madness: Segunda Edição – Ruas de Arkham: Expansão",
         "description":"Apenas lacrado.",
         "price":"100,00",
         "type":"Procura"
      }
   ],
   "type":"standard"
}
